# Generated by Django 3.0.2 on 2020-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎')]),
        ),
    ]
