# Generated by Django 3.0.2 on 2020-01-23 13:36

import best.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best', '0004_movieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, upload_to=best.models.cover_directory_path_with_uuid),
        ),
    ]
